/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ClassroomBoard: typeof import('./src/components/ClassroomBoard.vue')['default']
    RightPanel: typeof import('./src/components/RightPanel.vue')['default']
  }
}
